name: "Owen's Auto Merge Pull Request"
description: "Automatically merges a pull request using squash when checks pass."
author: "owen-6936"
branding:
  icon: "git-merge"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token with permissions to merge pull requests."
    required: true

runs:
  using: "composite"
  steps:
    - name: Merge pull request
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const branch = context.ref.replace('refs/heads/', '');
          const { data: prs } = await github.rest.pulls.list({
            ...context.repo,
            head: `${context.repo.owner}:${branch}`,
            state: 'open'
          });

          if (prs.length === 0) {
            core.setFailed(`No open pull request found for branch ${branch}`);
            return;
          }

          const pr = prs[0];

          try {
            await github.rest.pulls.merge({
              ...context.repo,
              pull_number: pr.number,
              merge_method: "squash"
            });
            console.log(`✅ Successfully merged PR #${pr.number}`);
          } catch (error) {
            if (error.status === 409) {
              console.log(`⚠️ Merge conflict detected in PR #${pr.number}. Manual resolution required.`);
              return;
            }
            throw error;
          }
