name: "Auto Merge Pull Request"
description: "Automatically merges a pull request using the squash merge method when all required status checks have passed."
author: "owen-6936"
branding:
  icon: "git-merge"
  color: "blue"

runs:
  using: "composite"
  steps:
    - name: Merge pull request
      uses: "actions/github-script@v6"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { pull_request } = context.payload;
          await github.rest.pulls.merge({
            ...context.repo,
            pull_number: pull_request.number,
            merge_method: "squash"
          });
