name: Automatic Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-branch: ${{ steps.extract-branch.outputs.branch }}
      pr-number: ${{ steps.get-pr.outputs.pr-number }}
    steps:
      - name: Extract Branch Name
        id: extract-branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier
        run: npm install prettier

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "chore: automated formatting" \
            --body "Automated PR from branch ${{ steps.extract-branch.outputs.branch }}" \
            --base main \
            --head ${{ steps.extract-branch.outputs.branch }} \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Pull Request Number
        id: get-pr
        run: |
          pr_number=$(gh pr list --head ${{ steps.extract-branch.outputs.branch }} --json number --jq '.[0].number')
          echo "pr-number=$pr_number" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-checks:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: echo "No linter configured" # Replace with: npm run lint

      - name: Run Tests
        run: echo "No tests configured" # Replace with: npm test

  auto-merge:
    runs-on: ubuntu-latest
    needs: [create-pr, run-checks]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-Merge the Pull Request
        uses: ./.github/actions/auto-merge
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ needs.create-pr.outputs.pr-number }}
